name: "Snowflake Terraform Demo Workflow"

on:
  push:
    branches:
      - main

jobs:
  snowflake-terraform-demo:
    name: "Snowflake Terraform Demo Job"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspaces: [./gh-actions-demo]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        working-directory: ${{ matrix.workspaces }}
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform plan
        id: plan
        working-directory: ${{ matrix.workspaces }}
        run: terraform validate -no-color
        
      - name: Terraform Apply
        id: apply
        working-directory: ${{ matrix.workspaces }}
        run: terraform apply -auto-approve
